app:
  gateway:
    url: http://172.16.212.76:8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.212.76/meeton?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: '1918'

  kafka:
    consumer:
      bootstrap-servers: 172.16.212.76:9092
    producer:
      bootstrap-servers: 172.16.212.76:9092

openapi:
  service:
    url: http://172.16.212.76:8000

