server:
  port: 8088

spring:
  application:
    name: board

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

  profiles:
    include: oauth

cloud:
  aws:
    s3:
      bucket: semicolon-bucket
    credentials:
      access-key: AKIA6JHGVMBA3CBCIUEK
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==

springdoc:
  api-docs:
    path: /board-api/v3/api-docs
  swagger-ui:
    path: /board-api/v3/swagger-ui.html

---
spring:
  profiles:
    active: dev, prod