server:
  port: 8088

spring:
  application:
    name: board
  datasource:
#    url: jdbc:h2:tcp://localhost/~/withsafe
#    username: sa
#    password: 1
#    driver-class-name: org.h2.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.212.76/meeton?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: '1918'

  jackson:
    time-zone: Asia/Seoul
    deserialization:
      adjust-dates-to-context-time-zone: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  kafka:
    consumer:
      bootstrap-servers: 172.16.212.76:9092
    producer:
      bootstrap-servers: 172.16.212.76:9092

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #??? ??

  profiles:
    include: oauth

cloud:
  aws:
    s3:
      bucket: bbang-test-bucket
    credentials:
      access-key: AKIA6ODU3C5N5QPBV7GI
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

jwt:
  secret: /vUwAz/Vx78zX5/E4v6kjfbyoTRpYtOK2WT9rYcXeNPzDMuv1BlehYL113paVVYvUTyUIYg3kSZglWjEAJxgMw==

springdoc:
  api-docs:
    path: /board-api/v3/api-docs
  swagger-ui:
    path: /board-api/v3/swagger-ui.html

openapi:
  service:
    url: http://172.16.212.76:8000


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://172.16.212.76:8761/eureka

  instance:
    hostname: 172.16.212.76
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}